config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :workshops do
    resources :student_workshops, only: [:create]
    resources :reviews, only: :create
  end
  resources :student_workshops, only: [:update]
  resources :reviews, only: :destroy
  get 'dashboard', to: 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :workshop
  validates :comment, presence: true
end

app/models/student_workshop.rb
class StudentWorkshop < ApplicationRecord
  belongs_to :user
  belongs_to :workshop
  has_many   :request_answers

  validates :workshop, :user, presence: true
def badge_status
  if status == "pending"
    return "badge-info"
  elsif status == "accepted"
    return "badge-success"
  elsif status == "rejected"
    return "badge-danger"
  end
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :student_workshops
  has_many :workshops

end

app/models/workshop.rb
class Workshop < ApplicationRecord
  belongs_to :user
  has_many :student_workshops, dependent: :destroy
  has_many :users, through: :student_workshops
  validates :name, presence: true
  validates :workshop_description, presence: true
  validates :location, presence: true
  validates :price, presence: true
  validates :starting_date, presence: true
  validates :ending_date, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  has_one_attached :photo
  has_many_attached :photos
  has_many :reviews, dependent: :destroy
  include PgSearch::Model
  pg_search_scope :global_search,
    against: [:name, :workshop_description],

    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def dashboard
    @workshops = current_user.workshops
    @validated_workshops = current_user.student_workshops.where(status: "accepted")
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @workshop = Workshop.find(params[:workshop_id])
    @review.workshop = @workshop
    if @review.save
      redirect_to workshop_path(@workshop)
    else
      render 'workshop/show'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to workshop_path(@review.workshop)
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end

end

app/controllers/student_workshops_controller.rb
class StudentWorkshopsController < ApplicationController
  def create
    @student_workshop = StudentWorkshop.new
    @workshop = Workshop.find(params[:workshop_id])
    @student_workshop.user = current_user
    @student_workshop.status = "pending"
    @student_workshop.workshop = @workshop
    if @student_workshop.save!
      redirect_to workshop_path(@workshop)
    else
      render :new
    end
  end

  def update
    @student_workshop = StudentWorkshop.find(params[:id])
    @student_workshop.update(student_workshop_params)
    redirect_to workshop_path(@student_workshop.workshop), notice: "status updated"
  end

  def student_workshop_params
    params.require(:student_workshop).permit(:status)
  end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController

  def index
    @workshop = Workshop.new
    @workshops = Workshop.all
    @markers = @workshops.geocoded.map do |workshop|
      {
        lat: workshop.latitude,
        lng: workshop.longitude
      }
    end
    if params[ :query].present?
      name = params[ :query]
      @workshops = Workshop.global_search(name)
    end

  end

  def show
    @workshop = Workshop.find(params[:id])
    @student_workshop = StudentWorkshop.new
    @review = Review.new(workshop: @workshop)
    @current_registration = @workshop.student_workshops.find_by(user: current_user)
  end

  def new
    @workshop = Workshop.new
  end

  def create
    @workshop = Workshop.new(workshop_params)
    @workshop.user = current_user
    if @workshop.save!
      redirect_to workshop_path(@workshop)
    else
      render :new
    end
  end

  def edit
    @workshop = Workshop.find(params[:id])
  end

  def update
    @workshop = Workshop.find(params[:id])
    @workshop.update(workshop_params)
    redirect_to workshop_path(@workshop)
  end

  def destroy
    @workshop = Workshop.find(params[:id])
    @workshop.destroy
    redirect_to workshops_path
  end


  private

  def workshop_params
    params.require(:workshop).permit(:name, :workshop_description, :location, :price, :starting_date, :ending_date, :youtube_url, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workshops</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%# unless params[:controller] == "pages" && params[:action] == "home" %>
    <%# end %>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="p-4">
<h1>Your dashboard</h1>
<h3>Created workshops</h3>
<div class="row">
  <% @workshops.each do |workshop| %>

  <div class="card m-2" style="width: 18rem;">
  <% workshop.photos.each do |photo| %>
    <%= cl_image_tag photo.key, height: 200, width: 350, crop: :fill, class: "card-img-top" %>
    <% end %>
    <div class="card-body flex-column">
      <h5 class="card-title"> <%= workshop.name %> </h5>
      <p class="card-text"><%= workshop.workshop_description %></p>
      <p><%= link_to "More details", workshop, class: "btn btn-primary" %></p>
        <small><%= link_to 'Edit', edit_workshop_path(workshop) %></small>
        <small><%= link_to 'Delete', workshop_path(workshop), method: :delete, data: { confirm: 'Are you sure?' } %></small>
    </div>
  </div>

<% end %>
</div>

<h3>Upcoming workshops</h3>
<div class="row">
<% @validated_workshops.each do | validated_workshop| %>
<% workshop = validated_workshop.workshop %>
<div class="card m-2" style="width: 18rem;">
  <% workshop.photos.each do |photo| %>
    <%= cl_image_tag photo.key, height: 200, width: 350, crop: :fill, class: "card-img-top" %>
    <% end %>
    <div class="card-body flex-column">
      <h5 class="card-title"> <%= workshop.name %> </h5>
      <p class="card-text"><%= workshop.workshop_description %></p>
      <p><%= link_to "More details", workshop, class: "btn btn-primary" %></p>
        <small><%= link_to 'Edit', edit_workshop_path(workshop) %></small>
        <small><%= link_to 'Delete', workshop_path(workshop), method: :delete, data: { confirm: 'Are you sure?' } %></small>
    </div>
  </div>
<% end %>
</div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path('workshop.jpg') %>);">

<div class="container">

  <div class="d-flex flex-column my-5">
    <h1>Welcome on AirWorkshops</h1>
    <p class="p-3">AirWorkshops connects students who want to participate to a meaningfull workshop and teachers who want to share their knowledge</p>
    <p><%= link_to "Find a workshop", workshops_path, class: "btn btn-primary" %></p>

  </div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "blockchain.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/workshops/edit.html.erb
<div class="container py-5">
      <div class="bg-white rounded p-3 shadow">
        <h3>Edit the workshop</h3>
        <%= simple_form_for(@workshop) do |f| %>
        <%= f.input :name %>
        <%= f.input :workshop_description %>
        <%= f.input :location %>
        <%= f.input :price %>
        <%= f.input :starting_date %>
        <%= f.input :ending_date %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.input :youtube_url %>
        <%= f.submit %>
        <% end %>
  </div>
</div>

app/views/workshops/index.html.erb
<div class="">
  <div class="m-2 d-flex justify-content-between">
  <%= form_tag workshops_path, method: :get, class: "d-flex" do %>
  <%= text_field_tag :query,
  params[:query],
  class: "form-control",
    placeholder: "Find a workshop"%>
  <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>

<!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
      Create new
    </button>
  </div>
<div id="map"
style="width: 30%; height: 600px;"
data-markers="<%= @markers.to_json %>"
data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
<div class="cards">

  <% @workshops.each do |workshop| %>

  <div class="card m-2" style="widows:  18rem;">
    <% workshop.photos.each do |photo| %>
    <%= cl_image_tag photo.key, height: 200, width: 350, crop: :fill, class: "card-img-top" %>
    <% end %>
    <div class="card-body flex-column">
      <h5 class="card-title"> <%= workshop.name %> </h5>
      <p class="card-text text-dark"><%= workshop.workshop_description %></p>
      <p><%= link_to "More details", workshop, class: "btn btn-primary" %></p>
      <% if workshop.user == current_user %>
      <small><%= link_to 'Edit', edit_workshop_path(workshop) %></small>
      <small><%= link_to 'Delete', workshop_path(workshop), method: :delete, data: { confirm: 'Are you sure?' } %></small>
      <% end %>
    </div>
  </div>
  <% end %>
</div>
</div>

<div class="container">
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create workshop</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(@workshop) do |f| %>
        <%= f.input :name %>
        <%= f.input :workshop_description %>
        <%= f.input :location %>
        <%= f.input :price %>
        <%= f.input :starting_date, as: :string, input_html: {type: :date} %>
        <%= f.input :ending_date, as: :string, input_html: {type: :date} %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.input :youtube_url %>
        <%= f.submit %>
        <% end %>
     </div>
    </div>
  </div>
</div>
</div>

app/views/workshops/new.html.erb
<div class="container py-5">
  <div class="bg-white rounded p-3 shadow">
    <h3>Create a new workshop</h3>
    <%= simple_form_for(@workshop) do |f| %>
    <%= f.input :name %>
    <%= f.input :workshop_description %>
    <%= f.input :location %>
    <%= f.input :price %>
    <%= f.input :starting_date %>
    <%= f.input :ending_date %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.input :youtube_url %>
    <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/workshops/show.html.erb
<div id="show-banner" class="cover mb-4 d-flex align-items-center justify-content-center" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.1)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png)">
  <div class="text-center text-white">
    <h1><%= @workshop.name %></h1>
  </div>
</div>
<div class="card-body ">
  <div class="d-flex justify-content-between">
    <div class="card-body flex-column">
      <p><%= @workshop.workshop_description %> </p>
      <p><%= "Location: #{@workshop.location}" %></p>
      <p><%= "Starting date: #{@workshop.starting_date}" %></p>
      <p><%= "Ending date: #{@workshop.ending_date}"%></p>
      <p><%= "Price: #{@workshop.price}€" %></p>
      <% if @workshop.user != current_user && @current_registration.nil? %>
      <div><%= link_to "Book now", workshop_student_workshops_path(@workshop), method: :post , class: "btn btn-primary" %></div>
      <% elsif @workshop.user == current_user %>
      <% @workshop.student_workshops.each do |booking| %>
      <%= booking.user.email  %>
      <%= simple_form_for booking do |f| %>
      <%= f.input :status, collection: ["accepted", "rejected"] %>
      <%= f.submit  %>
      <% end  %>
      <% end  %>
      <% else  %>
      <div>
        <span class="badge <%= @current_registration.badge_status %>"><%= @current_registration.status %></span>
        <% end %>
      </div>
    </div>
    <div>
      <p ><%=  link_to "Back to workshops", workshops_path, class:'btn btn-primary' %></p>
      <% @workshop.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
      <% end %>
      <% if @workshop.youtube_url %>
      <iframe width="560" height="315" src="<%= @workshop.youtube_url %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <% end  %>
    </div>
  </div>

</div>


  <hr class="my-5">
  <div class="row">
    <div class="col-12 col-sm-6">
      <h3>Reviews</h3>
      <% if @workshop.reviews.empty? %>
      <small><em class="text-muted">Be the first one to review this list</em></small>
      <% end %>
      <% @workshop.reviews.each do |review| %>
      <div>
        <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
        <p class="mb-0"><%= review.comment %></p>
      </div>
      <hr>
      <% end %>
    </div>
    <div class="col-12 col-sm-6">
      <div class="bg-white rounded p-3">
        <h5>Add your review</h5>
        <%= simple_form_for [@workshop, @review] do |f| %>
        <%= f.input :comment, placeholder: 'Add your review here...' %>
        <%= f.submit class:'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>